apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: gh-ghactions-quay-go-avmaznjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gh-ghactions-quay-go-avmaznjp 
  name: gh-ghactions-quay-go-avmaznjp
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gh-ghactions-quay-go-avmaznjp
    weight: 100 
